-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 23:06:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbpos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbpos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbpos` DEFAULT CHARACTER SET utf8 ;
USE `dbpos` ;

-- -----------------------------------------------------
-- Table `dbpos`.`jenis_produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`jenis_produk` (
  `id` INT(11) NOT NULL,
  `nama` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`kartu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`kartu` (
  `id` INT(11) NOT NULL,
  `kode` VARCHAR(6) NULL DEFAULT NULL,
  `nama` VARCHAR(30) NOT NULL,
  `diskon` DOUBLE NULL DEFAULT NULL,
  `iuran` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode` (`kode` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`pelanggan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`pelanggan` (
  `id` INT(11) NOT NULL,
  `kode` VARCHAR(10) NULL DEFAULT NULL,
  `nama_pelanggan` VARCHAR(50) NULL DEFAULT NULL,
  `jk` CHAR(1) NULL DEFAULT NULL,
  `tmp_lahir` VARCHAR(30) NULL DEFAULT NULL,
  `tgl_lahir` DATE NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `alamat` VARCHAR(40) NULL DEFAULT NULL,
  `kartu_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode` (`kode` ASC) VISIBLE,
  INDEX `fk_pelanggan_kartu_idx` (`kartu_id` ASC) VISIBLE,
  CONSTRAINT `fk_pelanggan_kartu`
    FOREIGN KEY (`kartu_id`)
    REFERENCES `dbpos`.`kartu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`pesanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`pesanan` (
  `id` INT(11) NOT NULL,
  `tanggal` DATE NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `pelanggan_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pesanan_pelanggan1_idx` (`pelanggan_id` ASC) VISIBLE,
  CONSTRAINT `fk_pesanan_pelanggan1`
    FOREIGN KEY (`pelanggan_id`)
    REFERENCES `dbpos`.`pelanggan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`pembayaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`pembayaran` (
  `id` INT(11) NOT NULL,
  `nokuitansi` VARCHAR(10) NULL DEFAULT NULL,
  `tanggal` DATE NULL DEFAULT NULL,
  `jumlah` DOUBLE NULL DEFAULT NULL,
  `ke` INT(11) NULL DEFAULT NULL,
  `pesanan_id1` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nokuitansi` (`nokuitansi` ASC) VISIBLE,
  INDEX `fk_pembayaran_pesanan1_idx` (`pesanan_id1` ASC) VISIBLE,
  CONSTRAINT `fk_pembayaran_pesanan1`
    FOREIGN KEY (`pesanan_id1`)
    REFERENCES `dbpos`.`pesanan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`produk` (
  `id` INT(11) NOT NULL,
  `kode` VARCHAR(10) NULL DEFAULT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `harga_beli` DOUBLE NULL DEFAULT NULL,
  `harga_jual` DOUBLE NULL DEFAULT NULL,
  `stok` INT(11) NULL DEFAULT NULL,
  `min_stok` INT(11) NULL DEFAULT NULL,
  `jenis_produk_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode` (`kode` ASC) VISIBLE,
  INDEX `fk_produk_jenis_produk1_idx` (`jenis_produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_produk_jenis_produk1`
    FOREIGN KEY (`jenis_produk_id`)
    REFERENCES `dbpos`.`jenis_produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`vendor` (
  `id` INT(11) NOT NULL,
  `nomor` VARCHAR(4) NULL DEFAULT NULL,
  `nama` VARCHAR(40) NULL DEFAULT NULL,
  `kota` VARCHAR(30) NULL DEFAULT NULL,
  `kontak` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`pembelian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`pembelian` (
  `id` INT(11) NOT NULL,
  `tanggal` VARCHAR(45) NULL DEFAULT NULL,
  `nomor` VARCHAR(10) NULL DEFAULT NULL,
  `jumlah` INT(11) NULL DEFAULT NULL,
  `harga` DOUBLE NULL DEFAULT NULL,
  `produk_id` INT(11) NOT NULL,
  `vendor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pembelian_produk1_idx` (`produk_id` ASC) VISIBLE,
  INDEX `fk_pembelian_vendor1_idx` (`vendor_id` ASC) VISIBLE,
  CONSTRAINT `fk_pembelian_produk1`
    FOREIGN KEY (`produk_id`)
    REFERENCES `dbpos`.`produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pembelian_vendor1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `dbpos`.`vendor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbpos`.`pesanan_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpos`.`pesanan_items` (
  `id` INT(11) NOT NULL,
  `qty` INT(11) NULL DEFAULT NULL,
  `harga` DOUBLE NULL DEFAULT NULL,
  `pesanan_id` INT(11) NOT NULL,
  `produk_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pesanan_items_pesanan1_idx` (`pesanan_id` ASC) VISIBLE,
  INDEX `fk_pesanan_items_produk1_idx` (`produk_id` ASC) VISIBLE,
  CONSTRAINT `fk_pesanan_items_pesanan1`
    FOREIGN KEY (`pesanan_id`)
    REFERENCES `dbpos`.`pesanan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesanan_items_produk1`
    FOREIGN KEY (`produk_id`)
    REFERENCES `dbpos`.`produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
